# Generated by Django 5.0.3 on 2026-02-08 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='created_at',
            new_name='date',
        ),
    ]
