# Generated by Django 6.0.2 on 2026-02-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_created_at_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
